## Import requeired libraries

In [1]:
import os
import pandas as pd
import numpy as np

# DATA LOADING

In [2]:
os.chdir("..")
# one folder back to lead data

In [ ]:
data = pd.read_csv("data/raw_data/loan_data_2007_2014.csv")

C:\Users\k\AppData\Local\Temp\ipykernel_15204\1016242786.py:1: DtypeWarning: Columns (0: desc) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("data/loan_data_2007_2014.csv")

# Explore Data

In [4]:
pd.options.display.max_columns = None

In [5]:
data.head()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-85,1.0,NaN,NaN,3.0,0.0,13648,83.7,9.0,f,0.0,0.0,5861.071414,5831.78,5000.00,861.07,0.00,0.00,0.00,Jan-15,171.62,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0.0,Apr-99,5.0,NaN,NaN,3.0,0.0,1687,9.4,4.0,f,0.0,0.0,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-13,119.66,NaN,Sep-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,real estate business,606xx,IL,8.72,0.0,Nov-01,2.0,NaN,NaN,2.0,0.0,2956,98.5,10.0,f,0.0,0.0,3003.653644,3003.65,2400.00,603.65,0.00,0.00,0.00,Jun-14,649.91,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,0.0,Feb-96,1.0,35.0,NaN,10.0,0.0,5598,21.0,37.0,f,0.0,0.0,12226.302210,12226.30,10000.00,2209.33,16.97,0.00,0.00,Jan-15,357.48,NaN,Jan-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,B5,University Medical Group,1 year,RENT,80000.0,Source Verified,Dec-11,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,0.0,Jan-96,0.0,38.0,NaN,15.0,0.0,27783,53.9,38.0,f,766.9,766.9,3242.170000,3242.17,2233.10,1009.07,0.00,0.00,0.00,Jan-16,67.79,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data.tail()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
466280,466280,8598660,1440975,18400,18400,18400.0,60 months,14.47,432.64,C,C2,Financial Advisor,4 years,MORTGAGE,110000.0,Source Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,773xx,TX,19.85,0.0,Apr-03,2.0,NaN,NaN,18.0,0.0,23208,77.6,36.0,w,12574.00,12574.00,10383.360000,10383.36,5826.00,4557.36,0.0,0.0,0.0,Jan-16,432.64,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,294998.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29900.0,NaN,NaN,NaN
466281,466281,9684700,11536848,22000,22000,22000.0,60 months,19.97,582.50,D,D5,Chief of Interpretation (Park Ranger),10+ years,MORTGAGE,78000.0,Verified,Jan-14,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,377xx,TN,18.45,0.0,Jun-97,5.0,NaN,116.0,18.0,1.0,18238,46.3,30.0,f,0.00,0.00,4677.920000,4677.92,1837.04,2840.88,0.0,0.0,0.0,Dec-14,17.50,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,221830.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39400.0,NaN,NaN,NaN
466282,466282,9584776,11436914,20700,20700,20700.0,60 months,16.99,514.34,D,D1,patrol,7 years,MORTGAGE,46000.0,Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/06/13 > I am going to c...,debt_consolidation,Debt consolidation,458xx,OH,25.65,0.0,Dec-01,2.0,65.0,NaN,18.0,0.0,6688,51.1,43.0,f,14428.31,14428.31,12343.980000,12343.98,6271.69,6072.29,0.0,0.0,0.0,Jan-16,514.34,Feb-16,Dec-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,73598.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13100.0,NaN,NaN,NaN
466283,466283,9604874,11457002,2000,2000,2000.0,36 months,7.90,62.59,A,A4,Server Engineer Lead,3 years,OWN,83000.0,Verified,Jan-14,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,credit_card,Credit card refinancing,913xx,CA,5.39,3.0,Feb-03,1.0,13.0,NaN,21.0,0.0,11404,21.5,27.0,w,0.00,0.00,2126.579838,2126.58,2000.00,126.58,0.0,0.0,0.0,Dec-14,1500.68,NaN,Apr-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,591610.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53100.0,NaN,NaN,NaN
466284,466284,9199665,11061576,10000,10000,9975.0,36 months,19.20,367.58,D,D3,NaN,10+ years,MORTGAGE,46000.0,Verified,Jan-14,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/04/13 > I will like a l...,other,Other,950xx,CA,22.78,1.0,Feb-00,0.0,9.0,NaN,6.0,0.0,11325,70.8,22.0,f,3984.38,3974.41,8821.620000,8799.57,6015.62,2806.00,0.0,0.0,0.0,Jan-16,367.58,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,57477.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16000.0,NaN,NaN,NaN

In [7]:
data.shape

(466285, 75)

In [8]:
data.columns

Index(['Unnamed: 0', 'id', 'member_id', 'loan_amnt', 'funded_amnt',
       'funded_amnt_inv', 'term', 'int_rate', 'installment', 'grade',
       'sub_grade', 'emp_title', 'emp_length', 'home_ownership', 'annual_inc',
       'verification_status', 'issue_d', 'loan_status', 'pymnt_plan', 'url',
       'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'dti',
       'delinq_2yrs', 'earliest_cr_line', 'inq_last_6mths',
       'mths_since_last_delinq', 'mths_since_last_record', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d',
       'collections_12_mths_ex_med', 'mths_since_last_major_derog',
       'policy_code', 'application_type', 'annual_inc_joint', 'dti_joint',
       'verification_status_joint', 'acc_now_delinq', 'tot_coll_amt',
       'tot_cur_bal', 'open_acc_6m', 'open_il_6m', 'open_il_12m',
       'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util',
       'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util',
       'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m'],
      dtype='str')

1. **Unnamed: 0** - Extra index column created when the dataset was saved; usually not useful for modeling.

2. **id** - Unique identifier for each loan.

3. **member_id** - Unique identifier for each borrower/member.

4. **loan_amnt** - The original loan amount requested by the borrower.

5. **funded_amnt** - The actual amount funded for the loan.

6. **funded_amnt_inv** - The portion of the loan amount funded by investors.

7. **term** - The duration of the loan, usually 36 or 60 months.

8. **int_rate** - The interest rate assigned to the loan.

9. **installment** - The fixed monthly payment the borrower must pay.

10. **grade** - Lending Club’s main credit risk grade, from A to G.

11. **sub_grade** - A more detailed credit risk grade, such as A1, B2, or C3.

12. **emp_title** - The job title provided by the borrower.

13. **emp_length** - The borrower’s length of employment.

14. **home_ownership** - The borrower’s home ownership status, such as RENT, OWN, or MORTGAGE.

15. **annual_inc** - The borrower’s annual income.

16. **verification_status** - Shows whether the borrower’s income was verified.

17. **issue_d** - The date when the loan was issued.

18. **loan_status** - The current or final status of the loan, such as Fully Paid, Charged Off, or Current.

19. **pymnt_plan** - Indicates whether the borrower has a special payment plan.

20. **url** - The URL related to the loan listing; usually not useful for modeling.

21. **desc** - The borrower’s description or explanation for the loan.

22. **purpose** - The stated purpose of the loan, such as debt consolidation or credit card refinancing.

23. **title** - The loan title provided by the borrower.

24. **zip_code** - The borrower’s ZIP code, usually partially hidden for privacy.

25. **addr_state** - The U.S. state where the borrower lives.

26. **dti** - Debt-to-income ratio; shows how much debt the borrower has compared to income.

27. **delinq_2yrs** - Number of times the borrower was delinquent in the past 2 years.

28. **earliest_cr_line** - The date when the borrower opened their first credit account.

29. **inq_last_6mths** - Number of credit inquiries in the last 6 months.

30. **mths_since_last_delinq** - Number of months since the borrower’s last delinquency.

31. **mths_since_last_record** - Number of months since the borrower’s last public record.
32. 
33. **open_acc** - Number of currently open credit accounts.

34. **pub_rec** - Number of derogatory public records, such as bankruptcies or tax liens.

35. **revol_bal** - Total revolving credit balance, usually credit card balance.

36. **revol_util** - Revolving credit utilization rate; shows how much available revolving credit is being used.
 
37. **total_acc** - Total number of credit accounts in the borrower’s credit file.

38. **initial_list_status** - Indicates whether the loan was initially listed as whole or fractional.

39. **out_prncp** - Remaining outstanding principal amount of the loan.

40. **out_prncp_inv** - Remaining outstanding principal amount funded by investors.

41. **total_pymnt** - Total amount paid by the borrower so far.

42. **total_pymnt_inv** - Total amount paid to investors so far.

43. **total_rec_prncp** - Total principal amount received from the borrower.

44. **total_rec_int** - Total interest amount received from the borrower.

45. **total_rec_late_fee** - Total late fees received from the borrower.

46. **recoveries** - Amount recovered after the borrower defaulted.

47. **collection_recovery_fee** - Fee charged for the collection or recovery process.

48. **last_pymnt_d** - Date of the borrower’s last payment.

49. **last_pymnt_amnt** - Amount of the borrower’s last payment.

50. **next_pymnt_d** - Date of the borrower’s next scheduled payment.

51. **last_credit_pull_d** - Date when the borrower’s credit report was last pulled.

52. **collections_12_mths_ex_med** - Number of collections in the last 12 months, excluding medical collections.

53. **mths_since_last_major_derog** - Number of months since the borrower’s last major negative credit event.

54. **policy_code** - Lending Club policy code assigned to the loan.

56. **application_type** - Indicates whether the loan application is individual or joint.

57. **annual_inc_joint** - Combined annual income for joint loan applicants.

58. **dti_joint** - Debt-to-income ratio for joint applicants.

59. **verification_status_joint** - Income verification status for joint applicants.

60. **acc_now_delinq** - Number of accounts where the borrower is currently delinquent.

61. **tot_coll_amt** - Total collection amounts owed by the borrower.

62. **tot_cur_bal** - Total current balance of all borrower accounts.

63. **open_acc_6m** - Number of open accounts opened in the last 6 months.

64. **open_il_6m** - Number of installment accounts opened in the last 6 months.

65. **open_il_12m** - Number of installment accounts opened in the last 12 months.

66. **open_il_24m** - Number of installment accounts opened in the last 24 months.

67. **mths_since_rcnt_il** - Number of months since the most recent installment account was opened.

68. **total_bal_il** - Total balance of installment loan accounts.

69. **il_util** - Installment loan utilization rate.

70. **open_rv_12m** - Number of revolving accounts opened in the last 12 months.

71. **open_rv_24m** - Number of revolving accounts opened in the last 24 months.

72. **max_bal_bc** - Maximum current balance on bankcard accounts.

73. **all_util** - Overall credit utilization across all credit accounts.

74. **total_rev_hi_lim** - Total revolving credit limit.

75. **inq_fi** - Number of personal finance inquiries.

76. **total_cu_tl** - Number of credit union trade lines.

77. **inq_last_12m** - Number of credit inquiries in the last 12 months.

In [9]:
data.shape

(466285, 75)

In [10]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 75 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   466285 non-null  int64
 1   id                           466285 non-null  int64
 2   member_id                    466285 non-null  int64
 3   loan_amnt                    466285 non-null  int64
 4   funded_amnt                  466285 non-null  int64
 5   funded_amnt_inv              466285 non-null  float64
 6   term                         466285 non-null  str
 7   int_rate                     466285 non-null  float64
 8   installment                  466285 non-null  float64
 9   grade                        466285 non-null  str
 10  sub_grade                    466285 non-null  str
 11  emp_title                    438697 non-null  str
 12  emp_length                   445277 non-null  str
 13  home_ownership               466285 non-null  str
 14  annual_inc                   466281 non-null  float64
 15  verification_status          466285 non-null  str
 16  issue_d                      466285 non-null  str
 17  loan_status                  466285 non-null  str
 18  pymnt_plan                   466285 non-null  str
 19  url                          466285 non-null  str
 20  desc                         125981 non-null  str
 21  purpose                      466285 non-null  str
 22  title                        466264 non-null  str
 23  zip_code                     466285 non-null  str
 24  addr_state                   466285 non-null  str
 25  dti                          466285 non-null  float64
 26  delinq_2yrs                  466256 non-null  float64
 27  earliest_cr_line             466256 non-null  str
 28  inq_last_6mths               466256 non-null  float64
 29  mths_since_last_delinq       215934 non-null  float64
 30  mths_since_last_record       62638 non-null   float64
 31  open_acc                     466256 non-null  float64
 32  pub_rec                      466256 non-null  float64
 33  revol_bal                    466285 non-null  int64
 34  revol_util                   465945 non-null  float64
 35  total_acc                    466256 non-null  float64
 36  initial_list_status          466285 non-null  str
 37  out_prncp                    466285 non-null  float64
 38  out_prncp_inv                466285 non-null  float64
 39  total_pymnt                  466285 non-null  float64
 40  total_pymnt_inv              466285 non-null  float64
 41  total_rec_prncp              466285 non-null  float64
 42  total_rec_int                466285 non-null  float64
 43  total_rec_late_fee           466285 non-null  float64
 44  recoveries                   466285 non-null  float64
 45  collection_recovery_fee      466285 non-null  float64
 46  last_pymnt_d                 465909 non-null  str
 47  last_pymnt_amnt              466285 non-null  float64
 48  next_pymnt_d                 239071 non-null  str
 49  last_credit_pull_d           466243 non-null  str
 50  collections_12_mths_ex_med   466140 non-null  float64
 51  mths_since_last_major_derog  98974 non-null   float64
 52  policy_code                  466285 non-null  int64
 53  application_type             466285 non-null  str
 54  annual_inc_joint             0 non-null       float64
 55  dti_joint                    0 non-null       float64
 56  verification_status_joint    0 non-null       float64
 57  acc_now_delinq               466256 non-null  float64
 58  tot_coll_amt                 396009 non-null  float64
 59  tot_cur_bal                  396009 non-null  float64
 60  open_acc_6m                  0 non-null       float64
 61  open_il_6m                   0 non-null       float64
 62  open_il_12m                  0 non-null       float64
 63  open_il_24m                  0 non-null       float64
 64  mths_since_rcnt_il           0 non-null       float64
 65  total_bal_il                 0 non-null       float64
 66  il_util                      0 non-null       float64
 67  open_rv_12m                  0 non-null       float64
 68  open_rv_24m                  0 non-null       float64
 69  max_bal_bc                   0 non-null       float64
 70  all_util                     0 non-null       float64
 71  total_rev_hi_lim             396009 non-null  float64
 72  inq_fi                       0 non-null       float64
 73  total_cu_tl                  0 non-null       float64
 74  inq_last_12m                 0 non-null       float64
dtypes: float64(46), int64(7), str(22)
memory usage: 266.8 MB

In [11]:
data.isnull().sum()

Unnamed: 0               0
id                       0
member_id                0
loan_amnt                0
funded_amnt              0
                     ...
all_util            466285
total_rev_hi_lim     70276
inq_fi              466285
total_cu_tl         466285
inq_last_12m        466285
Length: 75, dtype: int64

## General Processing

### Preprocessing few continuous variables

#### working on **emp_length** column 
    It shows how long the borrower has been working in their current job or employment situation.

In [12]:
data['emp_length'].unique()
# Displays unique values of a "emp_length" (emp_length means how long the borrower has been working) column

<StringArray>
['10+ years',  '< 1 year',    '1 year',   '3 years',   '8 years',   '9 years',
   '4 years',   '5 years',   '6 years',   '2 years',   '7 years',         nan]
Length: 12, dtype: str

In [13]:
# converting text values in emp_length column to int and saving a new column called emp_length_int
data['emp_length_int'] = data['emp_length'].str.replace(r'\+ years', '')
data['emp_length_int'] = data['emp_length'].str.replace('+', '')
data['emp_length_int'] = data['emp_length_int'].str.replace('< 1 year', str(0))
data['emp_length_int'] = data['emp_length_int'].str.replace('n/a', str(0))
data['emp_length_int'] = data['emp_length_int'].str.replace(' years', '')
data['emp_length_int'] = data['emp_length_int'].str.replace(' year', '')

In [14]:
data['emp_length_int'].unique()

<StringArray>
['10', '0', '1', '3', '8', '9', '4', '5', '6', '2', '7', nan]
Length: 12, dtype: str

In [15]:
type(data['emp_length_int'][0])
# Checks the datatype of a single element of a column.

str

In [16]:
# converting 'emp_length_int' column from str to int
data['emp_length_int'] = pd.to_numeric(data['emp_length_int'])

In [17]:
type(data['emp_length_int'][0])
# Checks the datatype of a single element of a column.

numpy.float64

#### working on **earliest_cr_line** column  ->
    It shows the date when the borrower opened their first credit account.

In [18]:
data['earliest_cr_line']

0         Jan-85
1         Apr-99
2         Nov-01
3         Feb-96
4         Jan-96
           ...
466280    Apr-03
466281    Jun-97
466282    Dec-01
466283    Feb-03
466284    Feb-00
Name: earliest_cr_line, Length: 466285, dtype: str

Jan-85                                                                                                                                                                                                   
Apr-01                                                                                                                                                                                                 
Dec-99                                                                                                                                                                                                 
Jun-10                                                                                                                                                                                                 

Meaning:                                                                                                                                                                                                 
        Jan-85 - the borrower opened their first credit account in January 1985.                                                                                                                         
        Apr-01 - the borrower opened their first credit account in April 2001.                                                                                                                       
        Jun-10 - the borrower opened their first credit account in June 2010.

In [19]:
# converting the earlist_cr_line column from text/string format into a real data format
data['earliest_cr_line_date'] = pd.to_datetime(
    data['earliest_cr_line'],
    format='%b-%y'
)

In [20]:
data['earliest_cr_line_date']

0        1985-01-01
1        1999-04-01
2        2001-11-01
3        1996-02-01
4        1996-01-01
            ...
466280   2003-04-01
466281   1997-06-01
466282   2001-12-01
466283   2003-02-01
466284   2000-02-01
Name: earliest_cr_line_date, Length: 466285, dtype: datetime64[us]

In [21]:
# checking data type
type(data['earliest_cr_line_date'][0])

pandas.Timestamp

In [22]:
#calculating the age/length of the borrower’s credit history
pd.to_datetime('2017-12-01') - data['earliest_cr_line_date']

0        12022 days
1         6819 days
2         5874 days
3         7974 days
4         8005 days
            ...
466280    5358 days
466281    7488 days
466282    5844 days
466283    5417 days
466284    6513 days
Name: earliest_cr_line_date, Length: 466285, dtype: timedelta64[us]

In [23]:
# Calculates the borrower's credit history length in months.
data['mths_since_earliest_cr_line'] = round(
    (pd.to_datetime('2017-12-01') - data['earliest_cr_line_date']).dt.days / (365.25 / 12)
)

In [24]:
data['mths_since_earliest_cr_line']

0         395.0
1         224.0
2         193.0
3         262.0
4         263.0
          ...
466280    176.0
466281    246.0
466282    192.0
466283    178.0
466284    214.0
Name: mths_since_earliest_cr_line, Length: 466285, dtype: float64

In [25]:
data['mths_since_earliest_cr_line'].describe()

count    466256.000000
mean        239.482430
std          93.974829
min        -612.000000
25%         183.000000
50%         225.000000
75%         285.000000
max         587.000000
Name: mths_since_earliest_cr_line, dtype: float64

In [26]:
data[['earliest_cr_line', 'earliest_cr_line_date', 'mths_since_earliest_cr_line']]

       earliest_cr_line earliest_cr_line_date  mths_since_earliest_cr_line
0                Jan-85            1985-01-01                        395.0
1                Apr-99            1999-04-01                        224.0
2                Nov-01            2001-11-01                        193.0
3                Feb-96            1996-02-01                        262.0
4                Jan-96            1996-01-01                        263.0
...                 ...                   ...                          ...
466280           Apr-03            2003-04-01                        176.0
466281           Jun-97            1997-06-01                        246.0
466282           Dec-01            2001-12-01                        192.0
466283           Feb-03            2003-02-01                        178.0
466284           Feb-00            2000-02-01                        214.0

[466285 rows x 3 columns]

In [27]:
# display problematic rows where the calculated credit history length is negative.
data.loc[
    data['mths_since_earliest_cr_line'] < 0,
    ['earliest_cr_line', 'earliest_cr_line_date', 'mths_since_earliest_cr_line']
]

       earliest_cr_line earliest_cr_line_date  mths_since_earliest_cr_line
1580             Sep-62            2062-09-01                       -537.0
1770             Sep-68            2068-09-01                       -609.0
2799             Sep-64            2064-09-01                       -561.0
3282             Sep-67            2067-09-01                       -597.0
3359             Feb-65            2065-02-01                       -566.0
...                 ...                   ...                          ...
464003           Jan-68            2068-01-01                       -601.0
464260           Jul-66            2066-07-01                       -583.0
465100           Oct-67            2067-10-01                       -598.0
465500           Sep-67            2067-09-01                       -597.0
465655           Jan-56            2056-01-01                       -457.0

[1169 rows x 3 columns]

In [28]:
# Replaces negative credit history values with the maximum valid value
data.loc[
    data['mths_since_earliest_cr_line'] < 0,
    'mths_since_earliest_cr_line'
] = data['mths_since_earliest_cr_line'].max()

In [29]:
# Calculates and shows the minimum value of a column.
min(data['mths_since_earliest_cr_line'])

73.0

#### working on **term** column 
    the duration of the loan.

In [30]:
data['term']

0          36 months
1          60 months
2          36 months
3          36 months
4          60 months
             ...
466280     60 months
466281     60 months
466282     60 months
466283     36 months
466284     36 months
Name: term, Length: 466285, dtype: str

In [31]:
data['term'].describe()

count         466285
unique             2
top        36 months
freq          337953
Name: term, dtype: object

In [32]:
# removing ' month' and converting from str to numberic data type
data['term_int'] = data['term'].str.replace(' months', '')
data['term_int'] = pd.to_numeric(data['term_int'])

In [33]:
type(data['term_int'][0])

numpy.int64

#### working on **issue_d** column
    It shows the date when the loan was issued/funded to the borrower.

In [34]:
data['issue_d']

0         Dec-11
1         Dec-11
2         Dec-11
3         Dec-11
4         Dec-11
           ...
466280    Jan-14
466281    Jan-14
466282    Jan-14
466283    Jan-14
466284    Jan-14
Name: issue_d, Length: 466285, dtype: str

In [35]:
# converting to data format
data['issue_d_date'] = pd.to_datetime(data['issue_d'], format='%b-%y')
# Calculate months since the loan was issued
data['mths_since_issue_d'] = round(
    (pd.to_datetime('2017-12-01') - data['issue_d_date']).dt.days / (365.25 / 12)
)

In [36]:
data['mths_since_issue_d'].describe()

count    466285.000000
mean         51.255187
std          14.340154
min          36.000000
25%          41.000000
50%          47.000000
75%          57.000000
max         126.000000
Name: mths_since_issue_d, dtype: float64

### Preprocessing few discrete variables

In [37]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 81 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   466285 non-null  int64
 1   id                           466285 non-null  int64
 2   member_id                    466285 non-null  int64
 3   loan_amnt                    466285 non-null  int64
 4   funded_amnt                  466285 non-null  int64
 5   funded_amnt_inv              466285 non-null  float64
 6   term                         466285 non-null  str
 7   int_rate                     466285 non-null  float64
 8   installment                  466285 non-null  float64
 9   grade                        466285 non-null  str
 10  sub_grade                    466285 non-null  str
 11  emp_title                    438697 non-null  str
 12  emp_length                   445277 non-null  str
 13  home_ownership               466285 non-null  str
 14  annual_inc                   466281 non-null  float64
 15  verification_status          466285 non-null  str
 16  issue_d                      466285 non-null  str
 17  loan_status                  466285 non-null  str
 18  pymnt_plan                   466285 non-null  str
 19  url                          466285 non-null  str
 20  desc                         125981 non-null  str
 21  purpose                      466285 non-null  str
 22  title                        466264 non-null  str
 23  zip_code                     466285 non-null  str
 24  addr_state                   466285 non-null  str
 25  dti                          466285 non-null  float64
 26  delinq_2yrs                  466256 non-null  float64
 27  earliest_cr_line             466256 non-null  str
 28  inq_last_6mths               466256 non-null  float64
 29  mths_since_last_delinq       215934 non-null  float64
 30  mths_since_last_record       62638 non-null   float64
 31  open_acc                     466256 non-null  float64
 32  pub_rec                      466256 non-null  float64
 33  revol_bal                    466285 non-null  int64
 34  revol_util                   465945 non-null  float64
 35  total_acc                    466256 non-null  float64
 36  initial_list_status          466285 non-null  str
 37  out_prncp                    466285 non-null  float64
 38  out_prncp_inv                466285 non-null  float64
 39  total_pymnt                  466285 non-null  float64
 40  total_pymnt_inv              466285 non-null  float64
 41  total_rec_prncp              466285 non-null  float64
 42  total_rec_int                466285 non-null  float64
 43  total_rec_late_fee           466285 non-null  float64
 44  recoveries                   466285 non-null  float64
 45  collection_recovery_fee      466285 non-null  float64
 46  last_pymnt_d                 465909 non-null  str
 47  last_pymnt_amnt              466285 non-null  float64
 48  next_pymnt_d                 239071 non-null  str
 49  last_credit_pull_d           466243 non-null  str
 50  collections_12_mths_ex_med   466140 non-null  float64
 51  mths_since_last_major_derog  98974 non-null   float64
 52  policy_code                  466285 non-null  int64
 53  application_type             466285 non-null  str
 54  annual_inc_joint             0 non-null       float64
 55  dti_joint                    0 non-null       float64
 56  verification_status_joint    0 non-null       float64
 57  acc_now_delinq               466256 non-null  float64
 58  tot_coll_amt                 396009 non-null  float64
 59  tot_cur_bal                  396009 non-null  float64
 60  open_acc_6m                  0 non-null       float64
 61  open_il_6m                   0 non-null       float64
 62  open_il_12m                  0 non-null       float64
 63  open_il_24m                  0 non-null       float64
 64  mths_since_rcnt_il           0 non-null       float64
 65  total_bal_il                 0 non-null       float64
 66  il_util                      0 non-null       float64
 67  open_rv_12m                  0 non-null       float64
 68  open_rv_24m                  0 non-null       float64
 69  max_bal_bc                   0 non-null       float64
 70  all_util                     0 non-null       float64
 71  total_rev_hi_lim             396009 non-null  float64
 72  inq_fi                       0 non-null       float64
 73  total_cu_tl                  0 non-null       float64
 74  inq_last_12m                 0 non-null       float64
 75  emp_length_int               445277 non-null  float64
 76  earliest_cr_line_date        466256 non-null  datetime64[us]
 77  mths_since_earliest_cr_line  466256 non-null  float64
 78  term_int                     466285 non-null  int64
 79  issue_d_date                 466285 non-null  datetime64[us]
 80  mths_since_issue_d           466285 non-null  float64
dtypes: datetime64[us](2), float64(49), int64(8), str(22)
memory usage: 288.2 MB

We are going to preocess the following discreate variables:
1. **grade** - Main credit risk grade of the borrower.

2. **sub_grade** - More detailed credit grade.

3. **home_ownership** - Borrower’s home ownership status.

4. **verification_status** - Whether borrower’s income was verified.

5. **loan_status** - Current or final loan repayment status.

6. **purpose** - Reason for taking the loan.

7. **addr_state** - Borrower’s U.S. state.

8. **initial_list_status** - Loan listing type: whole or fractional.                                                                                                                                    

Most likely, we are not going to use sub_grade, as it overlaps with grade.

#### Applying ONE-Hot Encoding by pd.get_dummies()

In [38]:
data_dummies = [
    pd.get_dummies(data['grade'], prefix='grade', prefix_sep=':', dtype=int),
    pd.get_dummies(data['sub_grade'], prefix='sub_grade', prefix_sep=':', dtype=int),
    pd.get_dummies(data['home_ownership'], prefix='home_ownership', prefix_sep=':', dtype=int),
    pd.get_dummies(data['verification_status'], prefix='verification_status', prefix_sep=':', dtype=int),
    pd.get_dummies(data['purpose'], prefix='purpose', prefix_sep=':', dtype=int),
    pd.get_dummies(data['addr_state'], prefix='addr_state', prefix_sep=':', dtype=int),
    pd.get_dummies(data['initial_list_status'], prefix='initial_list_status', prefix_sep=':', dtype=int),

]

In [39]:
# combining all One_hot encoded data into on dataframe
data_dummies = pd.concat(data_dummies, axis=1)

In [40]:
# combining data and data_dummies 
data = pd.concat([data, data_dummies], axis=1)

In [41]:
data.shape

(466285, 198)

### Checking for missing values and cleaning

In [42]:
pd.set_option('display.max_rows', None)
missing_value_columns = data.isnull().sum()
missing_value_columns[missing_value_columns > 0]

emp_title                       27588
emp_length                      21008
annual_inc                          4
desc                           340304
title                              21
delinq_2yrs                        29
earliest_cr_line                   29
inq_last_6mths                     29
mths_since_last_delinq         250351
mths_since_last_record         403647
open_acc                           29
pub_rec                            29
revol_util                        340
total_acc                          29
last_pymnt_d                      376
next_pymnt_d                   227214
last_credit_pull_d                 42
collections_12_mths_ex_med        145
mths_since_last_major_derog    367311
annual_inc_joint               466285
dti_joint                      466285
verification_status_joint      466285
acc_now_delinq                     29
tot_coll_amt                    70276
tot_cur_bal                     70276
open_acc_6m                    466285
open_il_6m                     466285
open_il_12m                    466285
open_il_24m                    466285
mths_since_rcnt_il             466285
total_bal_il                   466285
il_util                        466285
open_rv_12m                    466285
open_rv_24m                    466285
max_bal_bc                     466285
all_util                       466285
total_rev_hi_lim                70276
inq_fi                         466285
total_cu_tl                    466285
inq_last_12m                   466285
emp_length_int                  21008
earliest_cr_line_date              29
mths_since_earliest_cr_line        29
dtype: int64

In [43]:
missing_df = pd.DataFrame({
    'column_name': data.columns,
    'missing_count': data.isnull().sum().values
})

missing_df = missing_df[missing_df['missing_count'] > 0]
missing_df.sort_values(by='missing_count', ascending=False)

                    column_name  missing_count
67                  open_rv_12m         466285
68                  open_rv_24m         466285
69                   max_bal_bc         466285
70                     all_util         466285
72                       inq_fi         466285
73                  total_cu_tl         466285
54             annual_inc_joint         466285
60                  open_acc_6m         466285
55                    dti_joint         466285
56    verification_status_joint         466285
61                   open_il_6m         466285
74                 inq_last_12m         466285
64           mths_since_rcnt_il         466285
63                  open_il_24m         466285
66                      il_util         466285
65                 total_bal_il         466285
62                  open_il_12m         466285
30       mths_since_last_record         403647
51  mths_since_last_major_derog         367311
20                         desc         340304
29       mths_since_last_delinq         250351
48                 next_pymnt_d         227214
59                  tot_cur_bal          70276
71             total_rev_hi_lim          70276
58                 tot_coll_amt          70276
11                    emp_title          27588
12                   emp_length          21008
75               emp_length_int          21008
46                 last_pymnt_d            376
34                   revol_util            340
50   collections_12_mths_ex_med            145
49           last_credit_pull_d             42
28               inq_last_6mths             29
26                  delinq_2yrs             29
31                     open_acc             29
57               acc_now_delinq             29
32                      pub_rec             29
27             earliest_cr_line             29
35                    total_acc             29
76        earliest_cr_line_date             29
77  mths_since_earliest_cr_line             29
22                        title             21
14                   annual_inc              4

#### working on **total_rev_hi_lim** column, 
The total credit limit available across the borrower’s revolving credit accounts. So so it makes sense that the missing values are equal to funded_amnt (The actual amount of money that was funded/approved for the borrower.).

In [44]:
data['total_rev_hi_lim'] = data['total_rev_hi_lim'].fillna(data['funded_amnt'])

In [45]:
data['total_rev_hi_lim'].isnull().sum()

np.int64(0)

#### working on **annual_inc** column 
annual_inc means annual income — the borrower’s yearly income.

In [46]:
data['annual_inc'].isnull().sum()

np.int64(4)

In [47]:
# # Fills missing annual income values with the average annual income.
data['annual_inc'] = data['annual_inc'].fillna(data['annual_inc'].mean())

In [48]:
data['annual_inc'].isnull().sum()

np.int64(0)

#### Filling with zeros the follwong columns:
1. **mths_since_earliest_cr_line**
2. **acc_now_delinq**
3. **total_acc**
4. **pub_rec**
5. **open_acc**
6. **inq_last_6mths**
7. **delinq_2yrs**
7. **emp_length_int**

In [49]:
data['mths_since_earliest_cr_line']  = data['mths_since_earliest_cr_line'].fillna(0)
data['acc_now_delinq'] = data['acc_now_delinq'].fillna(0)
data['total_acc'] = data['total_acc'].fillna(0)
data['pub_rec'] = data['pub_rec'].fillna(0)
data['open_acc'] = data['open_acc'].fillna(0)
data['inq_last_6mths'] = data['inq_last_6mths'].fillna(0)
data['delinq_2yrs'] = data['delinq_2yrs'].fillna(0)
data['emp_length_int'] = data['emp_length_int'].fillna(0)

In [50]:
data[['mths_since_earliest_cr_line', 'acc_now_delinq', 'total_acc', 'pub_rec', 'open_acc', 'inq_last_6mths', 'delinq_2yrs', 'emp_length_int']].isnull().sum()

mths_since_earliest_cr_line    0
acc_now_delinq                 0
total_acc                      0
pub_rec                        0
open_acc                       0
inq_last_6mths                 0
delinq_2yrs                    0
emp_length_int                 0
dtype: int64

### Working on Target column

In [51]:
data['loan_status'].unique()

<StringArray>
[                                         'Fully Paid',
                                         'Charged Off',
                                             'Current',
                                             'Default',
                                  'Late (31-120 days)',
                                     'In Grace Period',
                                   'Late (16-30 days)',
  'Does not meet the credit policy. Status:Fully Paid',
 'Does not meet the credit policy. Status:Charged Off']
Length: 9, dtype: str

In [52]:
data['loan_status'].value_counts()

loan_status
Current                                                224226
Fully Paid                                             184739
Charged Off                                             42475
Late (31-120 days)                                       6900
In Grace Period                                          3146
Does not meet the credit policy. Status:Fully Paid       1988
Late (16-30 days)                                        1218
Default                                                   832
Does not meet the credit policy. Status:Charged Off       761
Name: count, dtype: int64

In [53]:
data['loan_status'].value_counts() / data['loan_status'].count()

loan_status
Current                                                0.480878
Fully Paid                                             0.396193
Charged Off                                            0.091092
Late (31-120 days)                                     0.014798
In Grace Period                                        0.006747
Does not meet the credit policy. Status:Fully Paid     0.004263
Late (16-30 days)                                      0.002612
Default                                                0.001784
Does not meet the credit policy. Status:Charged Off    0.001632
Name: count, dtype: float64

We convert the target column `loan_status` into a numerical binary variable called `good_bad`.

If the loan status represents a bad/default-like borrower, we assign **0**.  
If the loan status represents a good/non-default borrower, we assign **1**.

Examples:

**Charged Off** → 0  
**Default** → 0  
**Does not meet the credit policy. Status:Charged Off** → 0  
**Late (31-120 days)** → 0  

**Fully Paid** → 1  
**Current** → 1  
**In Grace Period** → 1  
**Late (16-30 days)** → 1  
**Does not meet the credit policy. Status:Fully Paid** → 1

In [54]:
data['good_bad'] = np.where(
    data['loan_status'].isin([
        'Charged Off', 
        'Default',
        'Does not meet the credit policy. Status:Charged Off',
        'Late (31-120 days)'
        ]
    ),
    0,
    1
)

In [55]:
data['good_bad'].value_counts()

good_bad
1    415317
0     50968
Name: count, dtype: int64

In [56]:
# Separate the independent variables (features) from the target variable.
# We remove 'good_bad' from X because it is the value we want to predict.
X = data.drop(['good_bad'], axis=1)

# Define the dependent variable (target).
# 'good_bad' contains the class labels: 1 = good borrower, 0 = bad/default-like borrower.
y = data['good_bad']

## Save processed data for Part 2

At this point, the basic preprocessing is complete and we have created:

- `X` — input variables/features
- `y` — target variable (`good_bad`)

We save them so the second notebook can continue from here without repeating Part 1.

In [57]:
# Create a folder for intermediate processed files.
os.makedirs("data/processed", exist_ok=True)

# Save the processed input variables and target variable for Part 2.
X.to_csv("data/processed/inputs_after_cleaning.csv", index=False)
y.to_csv("data/processed/target_after_cleaning.csv", index=False)

print("Saved:")
print("data/processed/inputs_after_cleaning.csv")
print("data/processed/target_after_cleaning.csv")

Saved:
data/processed/inputs_after_cleaning.csv
data/processed/target_after_cleaning.csv