## importing libraries

In [2]:
import numpy as np
import pandas as pd
import os

In [3]:
os.chdir("..")

In [4]:
os.getcwd()

'c:\\Users\\k\\Credit_Risk_Model'

In [32]:
loan_data_inputs_train = pd.read_csv('data/inputs_train.csv', index_col = 0)
loan_data_targets_train = pd.read_csv('data/target_train.csv')

loan_data_inputs_test = pd.read_csv('data/inputs_test.csv', index_col = 0)
loan_data_targets_test = pd.read_csv('data/target_test.csv')

## Explore data

In [33]:
loan_data_inputs_train.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,dti:21.7-22.4,dti:22.4-35,dti:>35,mths_since_last_record:Missing,mths_since_last_record:0-2,mths_since_last_record:3-20,mths_since_last_record:21-31,mths_since_last_record:32-80,mths_since_last_record:81-86,mths_since_last_record:>86
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
427211,12796369,14818505,24000,24000,24000.0,36 months,8.90,762.08,A,A5,...,1,0,0,1,0,0,0,0,0,0
206088,1439740,1691948,10000,10000,10000.0,36 months,14.33,343.39,C,C1,...,0,0,0,1,0,0,0,0,0,0
136020,5214749,6556909,20425,20425,20425.0,36 months,8.90,648.56,A,A5,...,0,0,0,1,0,0,0,0,0,0
412305,13827698,15890016,17200,17200,17200.0,36 months,16.59,609.73,D,D1,...,0,0,0,1,0,0,0,0,0,0
36159,422455,496525,8400,8400,7450.0,36 months,12.84,282.40,C,C2,...,0,1,0,1,0,0,0,0,0,0

In [34]:
loan_data_targets_train.head()

   good_bad
0         1
1         1
2         1
3         0
4         0

In [35]:
loan_data_inputs_train.shape

(373028, 314)

In [36]:
loan_data_targets_train.shape

(373028, 1)

In [37]:
loan_data_inputs_test.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,dti:21.7-22.4,dti:22.4-35,dti:>35,mths_since_last_record:Missing,mths_since_last_record:0-2,mths_since_last_record:3-20,mths_since_last_record:21-31,mths_since_last_record:32-80,mths_since_last_record:81-86,mths_since_last_record:>86
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
362514,19677589,21900299,32500,32500,32500.0,60 months,14.99,773.01,C,C5,...,0,0,0,1,0,0,0,0,0,0
288564,29755527,32278795,11000,11000,11000.0,60 months,20.99,297.53,E,E4,...,0,1,0,1,0,0,0,0,0,0
213591,1343334,1588314,30000,30000,30000.0,36 months,14.65,1034.83,C,C2,...,0,0,0,1,0,0,0,0,0,0
263083,33131681,35775007,14400,14400,14400.0,60 months,14.49,338.74,C,C4,...,0,0,0,1,0,0,0,0,0,0
165001,3293168,4066358,15000,15000,14900.0,36 months,8.90,476.30,A,A5,...,0,0,0,1,0,0,0,0,0,0

In [38]:
loan_data_targets_test.head()

   good_bad
0         1
1         1
2         1
3         1
4         1

In [39]:
loan_data_inputs_test.shape

(93257, 314)

In [40]:
loan_data_targets_test.shape

(93257, 1)

In [41]:
loan_data_inputs_train.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       ...
       'dti:21.7-22.4', 'dti:22.4-35', 'dti:>35',
       'mths_since_last_record:Missing', 'mths_since_last_record:0-2',
       'mths_since_last_record:3-20', 'mths_since_last_record:21-31',
       'mths_since_last_record:32-80', 'mths_since_last_record:81-86',
       'mths_since_last_record:>86'],
      dtype='str', length=314)

## selecting the features

In [42]:
# Here we select a limited set of input variables in a new dataframe.
inputs_train_with_ref_cat = loan_data_inputs_train.loc[: , ['grade:A',
'grade:B',
'grade:C',
'grade:D',
'grade:E',
'grade:F',
'grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'home_ownership:OWN',
'home_ownership:MORTGAGE',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'addr_state:NM_VA',
'addr_state:NY',
'addr_state:OK_TN_MO_LA_MD_NC',
'addr_state:CA',
'addr_state:UT_KY_AZ_NJ',
'addr_state:AR_MI_PA_OH_MN',
'addr_state:RI_MA_DE_SD_IN',
'addr_state:GA_WA_OR',
'addr_state:WI_MT',
'addr_state:TX',
'addr_state:IL_CT',
'addr_state:KS_SC_CO_VT_AK_MS',
'addr_state:WV_NH_WY_DC_ME_ID',
'verification_status:Not Verified',
'verification_status:Source Verified',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'purpose:credit_card',
'purpose:debt_consolidation',
'purpose:oth__med__vacation',
'purpose:major_purch__car__home_impr',
'initial_list_status:f',
'initial_list_status:w',
'term:36',
'term:60',
'emp_length:0',
'emp_length:1',
'emp_length:2-4',
'emp_length:5-6',
'emp_length:7-9',
'emp_length:10',
'mths_since_issue_d:<38',
'mths_since_issue_d:38-39',
'mths_since_issue_d:40-41',
'mths_since_issue_d:42-48',
'mths_since_issue_d:49-52',
'mths_since_issue_d:53-64',
'mths_since_issue_d:65-84',
'mths_since_issue_d:>84',
'int_rate:<9.548',
'int_rate:9.548-12.025',
'int_rate:12.025-15.74',
'int_rate:15.74-20.281',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'mths_since_earliest_cr_line:141-164',
'mths_since_earliest_cr_line:165-247',
'mths_since_earliest_cr_line:248-270',
'mths_since_earliest_cr_line:271-352',
'mths_since_earliest_cr_line:>352',
'delinq_2yrs:0',
'delinq_2yrs:1-3',
'delinq_2yrs:>=4',
'inq_last_6mths:0',
'inq_last_6mths:1-2',
'inq_last_6mths:3-6',
'inq_last_6mths:>6',
'open_acc:0',
'open_acc:1-3',
'open_acc:4-12',
'open_acc:13-17',
'open_acc:18-22',
'open_acc:23-25',
'open_acc:26-30',
'open_acc:>=31',
'pub_rec:0-2',
'pub_rec:3-4',
'pub_rec:>=5',
'total_acc:<=27',
'total_acc:28-51',
'total_acc:>=52',
'acc_now_delinq:0',
'acc_now_delinq:>=1',
'total_rev_hi_lim:<=5K',
'total_rev_hi_lim:5K-10K',
'total_rev_hi_lim:10K-20K',
'total_rev_hi_lim:20K-30K',
'total_rev_hi_lim:30K-40K',
'total_rev_hi_lim:40K-55K',
'total_rev_hi_lim:55K-95K',
'total_rev_hi_lim:>95K',
'annual_inc:<20K',
'annual_inc:20K-30K',
'annual_inc:30K-40K',
'annual_inc:40K-50K',
'annual_inc:50K-60K',
'annual_inc:60K-70K',
'annual_inc:70K-80K',
'annual_inc:80K-90K',
'annual_inc:90K-100K',
'annual_inc:100K-120K',
'annual_inc:120K-140K',
'annual_inc:>140K',
'dti:<=1.4',
'dti:1.4-3.5',
'dti:3.5-7.7',
'dti:7.7-10.5',
'dti:10.5-16.1',
'dti:16.1-20.3',
'dti:20.3-21.7',
'dti:21.7-22.4',
'dti:22.4-35',
'dti:>35',
'mths_since_last_delinq:Missing',
'mths_since_last_delinq:0-3',
'mths_since_last_delinq:4-30',
'mths_since_last_delinq:31-56',
'mths_since_last_delinq:>=57',
'mths_since_last_record:Missing',
'mths_since_last_record:0-2',
'mths_since_last_record:3-20',
'mths_since_last_record:21-31',
'mths_since_last_record:32-80',
'mths_since_last_record:81-86',
'mths_since_last_record:>86',
]]

In [43]:
# Here we store the names of the reference category dummy variables in a list.
ref_categories = ['grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'initial_list_status:f',
'term:60',
'emp_length:0',
'mths_since_issue_d:>84',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'delinq_2yrs:>=4',
'inq_last_6mths:>6',
'open_acc:0',
'pub_rec:0-2',
'total_acc:<=27',
'acc_now_delinq:0',
'total_rev_hi_lim:<=5K',
'annual_inc:<20K',
'dti:>35',
'mths_since_last_delinq:0-3',
'mths_since_last_record:0-2']

In [44]:
inputs_train = inputs_train_with_ref_cat.drop(ref_categories, axis = 1)
# From the dataframe with input variables, we drop the variables with variable names in the list with reference categories. 
inputs_train.head()

,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,home_ownership:OWN,home_ownership:MORTGAGE,addr_state:NM_VA,addr_state:NY,...,mths_since_last_delinq:Missing,mths_since_last_delinq:4-30,mths_since_last_delinq:31-56,mths_since_last_delinq:>=57,mths_since_last_record:Missing,mths_since_last_record:3-20,mths_since_last_record:21-31,mths_since_last_record:32-80,mths_since_last_record:81-86,mths_since_last_record:>86
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
427211,1,0,0,0,0,0,0,1,0,0,...,1,0,0,0,1,0,0,0,0,0
206088,0,0,1,0,0,0,0,1,0,0,...,0,1,0,0,1,0,0,0,0,0
136020,1,0,0,0,0,0,0,1,0,0,...,0,0,1,0,1,0,0,0,0,0
412305,0,0,0,1,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
36159,0,0,1,0,0,0,0,1,0,0,...,1,0,0,0,1,0,0,0,0,0

# PD Model Estimation
## Logistic Regression

In [45]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [46]:
reg = LogisticRegression()

In [47]:
pd.options.display.max_rows = None

In [48]:
reg.fit(inputs_train, loan_data_targets_train)

c:\Users\k\anaconda3\envs\creditrisk\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [49]:
reg.intercept_

array([-0.44965256])

In [50]:
reg.coef_

array([[ 0.95942412,  0.75419603,  0.57382612,  0.39296023,  0.23858349,
         0.06514085,  0.09071207,  0.10272728,  0.0434879 ,  0.0700851 ,
         0.06634504,  0.070449  ,  0.08742161,  0.14728105,  0.11435442,
         0.19645364,  0.24278441,  0.23403271,  0.27507017,  0.3358681 ,
         0.49049264,  0.08290307, -0.01561263,  0.27313228,  0.17101618,
         0.17684615,  0.2297484 ,  0.0511012 ,  0.07122902,  0.10982552,
         0.13460411,  0.10251324,  0.06878645,  0.12898412,  1.12592344,
         0.93341095,  0.83522191,  0.6408304 ,  0.48088444,  0.23577322,
        -0.0161227 ,  0.97805026,  0.62682538,  0.36322798,  0.15220974,
         0.07708757,  0.05876805,  0.10545672,  0.14241762,  0.14888828,
        -0.03435282, -0.06297439,  0.28330283,  0.14081337, -0.06773606,
         0.06935818, -0.04301044, -0.06616424, -0.09375449, -0.07705438,
        -0.05423848, -0.10916809,  0.13551236,  0.09324756, -0.02115753,
         0.03160623,  0.15998118,  0.04276516,  0.00831955,  0.00248415,
         0.02005901,  0.03326083,  0.06083756,  0.19987181, -0.18183228,
        -0.11182236, -0.0132252 ,  0.05473855,  0.13331351,  0.20696755,
         0.27923625,  0.29419313,  0.37376122,  0.49307952,  0.3997173 ,
         0.05271629,  0.17325174,  0.19905833,  0.14111177,  0.05932058,
        -0.03817848, -0.0487902 , -0.08392279, -0.12049102,  0.07202333,
         0.1207556 ,  0.14773317,  0.09985301,  0.15185918,  0.22886104,
         0.15565744,  0.32993622, -0.02865184,  0.06294568]])

In [51]:
feature_name = inputs_train.columns.values

In [52]:
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)
# Creates a dataframe with a column titled 'Feature name' and row values contained in the 'feature_name' variable.
summary_table['Coefficients'] = np.transpose(reg.coef_)
# Creates a new column in the dataframe, called 'Coefficients',
# with row values the transposed coefficients from the 'LogisticRegression' object.
summary_table.index = summary_table.index + 1
# Increases the index of every row of the dataframe with 1.
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
# Assigns values of the row with index 0 of the dataframe.
summary_table = summary_table.sort_index()
# Sorts the dataframe by index.
summary_table

                            Feature name  Coefficients
0                              Intercept     -0.449653
1                                grade:A      0.959424
2                                grade:B      0.754196
3                                grade:C      0.573826
4                                grade:D      0.392960
5                                grade:E      0.238583
6                                grade:F      0.065141
7                     home_ownership:OWN      0.090712
8                home_ownership:MORTGAGE      0.102727
9                       addr_state:NM_VA      0.043488
10                         addr_state:NY      0.070085
11          addr_state:OK_TN_MO_LA_MD_NC      0.066345
12                         addr_state:CA      0.070449
13                addr_state:UT_KY_AZ_NJ      0.087422
14             addr_state:AR_MI_PA_OH_MN      0.147281
15             addr_state:RI_MA_DE_SD_IN      0.114354
16                   addr_state:GA_WA_OR      0.196454
17                      addr_state:WI_MT      0.242784
18                         addr_state:TX      0.234033
19                      addr_state:IL_CT      0.275070
20          addr_state:KS_SC_CO_VT_AK_MS      0.335868
21          addr_state:WV_NH_WY_DC_ME_ID      0.490493
22      verification_status:Not Verified      0.082903
23   verification_status:Source Verified     -0.015613
24                   purpose:credit_card      0.273132
25            purpose:debt_consolidation      0.171016
26            purpose:oth__med__vacation      0.176846
27   purpose:major_purch__car__home_impr      0.229748
28                 initial_list_status:w      0.051101
29                               term:36      0.071229
30                          emp_length:1      0.109826
31                        emp_length:2-4      0.134604
32                        emp_length:5-6      0.102513
33                        emp_length:7-9      0.068786
34                         emp_length:10      0.128984
35                mths_since_issue_d:<38      1.125923
36              mths_since_issue_d:38-39      0.933411
37              mths_since_issue_d:40-41      0.835222
38              mths_since_issue_d:42-48      0.640830
39              mths_since_issue_d:49-52      0.480884
40              mths_since_issue_d:53-64      0.235773
41              mths_since_issue_d:65-84     -0.016123
42                       int_rate:<9.548      0.978050
43                 int_rate:9.548-12.025      0.626825
44                 int_rate:12.025-15.74      0.363228
45                 int_rate:15.74-20.281      0.152210
46   mths_since_earliest_cr_line:141-164      0.077088
47   mths_since_earliest_cr_line:165-247      0.058768
48   mths_since_earliest_cr_line:248-270      0.105457
49   mths_since_earliest_cr_line:271-352      0.142418
50      mths_since_earliest_cr_line:>352      0.148888
51                         delinq_2yrs:0     -0.034353
52                       delinq_2yrs:1-3     -0.062974
53                      inq_last_6mths:0      0.283303
54                    inq_last_6mths:1-2      0.140813
55                    inq_last_6mths:3-6     -0.067736
56                          open_acc:1-3      0.069358
57                         open_acc:4-12     -0.043010
58                        open_acc:13-17     -0.066164
59                        open_acc:18-22     -0.093754
60                        open_acc:23-25     -0.077054
61                        open_acc:26-30     -0.054238
62                         open_acc:>=31     -0.109168
63                           pub_rec:3-4      0.135512
64                           pub_rec:>=5      0.093248
65                       total_acc:28-51     -0.021158
66                        total_acc:>=52      0.031606
67                    acc_now_delinq:>=1      0.159981
68               total_rev_hi_lim:5K-10K      0.042765
69              total_rev_hi_lim:10K-20K      0.008320
70              total_rev_hi_lim:20K-30K      0.002484
71              total_rev_hi_lim:30K-40K      0.020059
72              total_rev_hi_lim:40K-55K      0.033261
73              total_rev_hi_lim:55K-95K      0.060838
74                 total_rev_hi_lim:>95K      0.199872
75                    annual_inc:20K-30K     -0.181832
76                    annual_inc:30K-40K     -0.111822
77                    annual_inc:40K-50K     -0.013225
78                    annual_inc:50K-60K      0.054739
79                    annual_inc:60K-70K      0.133314
80                    annual_inc:70K-80K      0.206968
81                    annual_inc:80K-90K      0.279236
82                   annual_inc:90K-100K      0.294193
83                  annual_inc:100K-120K      0.373761
84                  annual_inc:120K-140K      0.493080
85                      annual_inc:>140K      0.399717
86                             dti:<=1.4      0.052716
87                           dti:1.4-3.5      0.173252
88                           dti:3.5-7.7      0.199058
89                          dti:7.7-10.5      0.141112
90                         dti:10.5-16.1      0.059321
91                         dti:16.1-20.3     -0.038178
92                         dti:20.3-21.7     -0.048790
93                         dti:21.7-22.4     -0.083923
94                           dti:22.4-35     -0.120491
95        mths_since_last_delinq:Missing      0.072023
96           mths_since_last_delinq:4-30      0.120756
97          mths_since_last_delinq:31-56      0.147733
98           mths_since_last_delinq:>=57      0.099853
99        mths_since_last_record:Missing      0.151859
100          mths_since_last_record:3-20      0.228861
101         mths_since_last_record:21-31      0.155657
102         mths_since_last_record:32-80      0.329936
103         mths_since_last_record:81-86     -0.028652
104           mths_since_last_record:>86      0.062946

## Build a Logistic Regression Model with P-Values

In [53]:
# P values for sklearn logistic regression.

# Class to display p-values for logistic regression in sklearn.

from sklearn import linear_model
import scipy.stats as stat

class LogisticRegression_with_p_values:
    
    def __init__(self,*args,**kwargs):#,**kwargs):
        self.model = linear_model.LogisticRegression(*args,**kwargs)#,**args)

    def fit(self,X,y):
        self.model.fit(X,y)
        
        #### Get p-values for the fitted model ####
        denom = (2.0 * (1.0 + np.cosh(self.model.decision_function(X))))
        denom = np.tile(denom,(X.shape[1],1)).T
        F_ij = np.dot((X / denom).T,X) ## Fisher Information Matrix
        Cramer_Rao = np.linalg.inv(F_ij) ## Inverse Information Matrix
        sigma_estimates = np.sqrt(np.diagonal(Cramer_Rao))
        z_scores = self.model.coef_[0] / sigma_estimates # z-score for eaach model coefficient
        p_values = [stat.norm.sf(abs(x)) * 2 for x in z_scores] ### two tailed test for p-values
        
        self.coef_ = self.model.coef_
        self.intercept_ = self.model.intercept_
        self.p_values = p_values

In [54]:
reg = LogisticRegression_with_p_values()

In [55]:
reg.fit(inputs_train, loan_data_targets_train)

c:\Users\k\anaconda3\envs\creditrisk\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [56]:
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)
summary_table['Coefficients'] = np.transpose(reg.coef_)
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

                            Feature name  Coefficients
0                              Intercept     -0.449653
1                                grade:A      0.959424
2                                grade:B      0.754196
3                                grade:C      0.573826
4                                grade:D      0.392960
5                                grade:E      0.238583
6                                grade:F      0.065141
7                     home_ownership:OWN      0.090712
8                home_ownership:MORTGAGE      0.102727
9                       addr_state:NM_VA      0.043488
10                         addr_state:NY      0.070085
11          addr_state:OK_TN_MO_LA_MD_NC      0.066345
12                         addr_state:CA      0.070449
13                addr_state:UT_KY_AZ_NJ      0.087422
14             addr_state:AR_MI_PA_OH_MN      0.147281
15             addr_state:RI_MA_DE_SD_IN      0.114354
16                   addr_state:GA_WA_OR      0.196454
17                      addr_state:WI_MT      0.242784
18                         addr_state:TX      0.234033
19                      addr_state:IL_CT      0.275070
20          addr_state:KS_SC_CO_VT_AK_MS      0.335868
21          addr_state:WV_NH_WY_DC_ME_ID      0.490493
22      verification_status:Not Verified      0.082903
23   verification_status:Source Verified     -0.015613
24                   purpose:credit_card      0.273132
25            purpose:debt_consolidation      0.171016
26            purpose:oth__med__vacation      0.176846
27   purpose:major_purch__car__home_impr      0.229748
28                 initial_list_status:w      0.051101
29                               term:36      0.071229
30                          emp_length:1      0.109826
31                        emp_length:2-4      0.134604
32                        emp_length:5-6      0.102513
33                        emp_length:7-9      0.068786
34                         emp_length:10      0.128984
35                mths_since_issue_d:<38      1.125923
36              mths_since_issue_d:38-39      0.933411
37              mths_since_issue_d:40-41      0.835222
38              mths_since_issue_d:42-48      0.640830
39              mths_since_issue_d:49-52      0.480884
40              mths_since_issue_d:53-64      0.235773
41              mths_since_issue_d:65-84     -0.016123
42                       int_rate:<9.548      0.978050
43                 int_rate:9.548-12.025      0.626825
44                 int_rate:12.025-15.74      0.363228
45                 int_rate:15.74-20.281      0.152210
46   mths_since_earliest_cr_line:141-164      0.077088
47   mths_since_earliest_cr_line:165-247      0.058768
48   mths_since_earliest_cr_line:248-270      0.105457
49   mths_since_earliest_cr_line:271-352      0.142418
50      mths_since_earliest_cr_line:>352      0.148888
51                         delinq_2yrs:0     -0.034353
52                       delinq_2yrs:1-3     -0.062974
53                      inq_last_6mths:0      0.283303
54                    inq_last_6mths:1-2      0.140813
55                    inq_last_6mths:3-6     -0.067736
56                          open_acc:1-3      0.069358
57                         open_acc:4-12     -0.043010
58                        open_acc:13-17     -0.066164
59                        open_acc:18-22     -0.093754
60                        open_acc:23-25     -0.077054
61                        open_acc:26-30     -0.054238
62                         open_acc:>=31     -0.109168
63                           pub_rec:3-4      0.135512
64                           pub_rec:>=5      0.093248
65                       total_acc:28-51     -0.021158
66                        total_acc:>=52      0.031606
67                    acc_now_delinq:>=1      0.159981
68               total_rev_hi_lim:5K-10K      0.042765
69              total_rev_hi_lim:10K-20K      0.008320
70              total_rev_hi_lim:20K-30K      0.002484
71              total_rev_hi_lim:30K-40K      0.020059
72              total_rev_hi_lim:40K-55K      0.033261
73              total_rev_hi_lim:55K-95K      0.060838
74                 total_rev_hi_lim:>95K      0.199872
75                    annual_inc:20K-30K     -0.181832
76                    annual_inc:30K-40K     -0.111822
77                    annual_inc:40K-50K     -0.013225
78                    annual_inc:50K-60K      0.054739
79                    annual_inc:60K-70K      0.133314
80                    annual_inc:70K-80K      0.206968
81                    annual_inc:80K-90K      0.279236
82                   annual_inc:90K-100K      0.294193
83                  annual_inc:100K-120K      0.373761
84                  annual_inc:120K-140K      0.493080
85                      annual_inc:>140K      0.399717
86                             dti:<=1.4      0.052716
87                           dti:1.4-3.5      0.173252
88                           dti:3.5-7.7      0.199058
89                          dti:7.7-10.5      0.141112
90                         dti:10.5-16.1      0.059321
91                         dti:16.1-20.3     -0.038178
92                         dti:20.3-21.7     -0.048790
93                         dti:21.7-22.4     -0.083923
94                           dti:22.4-35     -0.120491
95        mths_since_last_delinq:Missing      0.072023
96           mths_since_last_delinq:4-30      0.120756
97          mths_since_last_delinq:31-56      0.147733
98           mths_since_last_delinq:>=57      0.099853
99        mths_since_last_record:Missing      0.151859
100          mths_since_last_record:3-20      0.228861
101         mths_since_last_record:21-31      0.155657
102         mths_since_last_record:32-80      0.329936
103         mths_since_last_record:81-86     -0.028652
104           mths_since_last_record:>86      0.062946

In [57]:
p_values = reg.p_values

In [58]:
p_values = np.append(np.nan, np.array(p_values))

In [59]:
summary_table['p_values'] = p_values

In [60]:
summary_table

                            Feature name  Coefficients       p_values
0                              Intercept     -0.449653            NaN
1                                grade:A      0.959424   1.123162e-25
2                                grade:B      0.754196   2.546667e-34
3                                grade:C      0.573826   1.414468e-23
4                                grade:D      0.392960   5.679713e-13
5                                grade:E      0.238583   1.032942e-06
6                                grade:F      0.065141   2.004100e-01
7                     home_ownership:OWN      0.090712   7.089808e-06
8                home_ownership:MORTGAGE      0.102727   5.937190e-16
9                       addr_state:NM_VA      0.043488   1.745103e-01
10                         addr_state:NY      0.070085   3.885191e-03
11          addr_state:OK_TN_MO_LA_MD_NC      0.066345   4.198037e-03
12                         addr_state:CA      0.070449   8.937483e-04
13                addr_state:UT_KY_AZ_NJ      0.087422   4.535210e-04
14             addr_state:AR_MI_PA_OH_MN      0.147281   6.664833e-11
15             addr_state:RI_MA_DE_SD_IN      0.114354   1.304977e-04
16                   addr_state:GA_WA_OR      0.196454   1.895935e-13
17                      addr_state:WI_MT      0.242784   3.218526e-07
18                         addr_state:TX      0.234033   2.243400e-19
19                      addr_state:IL_CT      0.275070   5.431586e-21
20          addr_state:KS_SC_CO_VT_AK_MS      0.335868   1.677965e-27
21          addr_state:WV_NH_WY_DC_ME_ID      0.490493   8.998227e-21
22      verification_status:Not Verified      0.082903   1.707548e-08
23   verification_status:Source Verified     -0.015613   2.466480e-01
24                   purpose:credit_card      0.273132   1.406704e-21
25            purpose:debt_consolidation      0.171016   8.762676e-11
26            purpose:oth__med__vacation      0.176846   1.731071e-08
27   purpose:major_purch__car__home_impr      0.229748   3.051693e-13
28                 initial_list_status:w      0.051101   9.118707e-05
29                               term:36      0.071229   5.116585e-07
30                          emp_length:1      0.109826   2.345302e-05
31                        emp_length:2-4      0.134604   1.001288e-12
32                        emp_length:5-6      0.102513   1.684249e-06
33                        emp_length:7-9      0.068786   9.385066e-04
34                         emp_length:10      0.128984   2.563952e-12
35                mths_since_issue_d:<38      1.125923  9.825825e-190
36              mths_since_issue_d:38-39      0.933411  2.222756e-162
37              mths_since_issue_d:40-41      0.835222  9.785001e-137
38              mths_since_issue_d:42-48      0.640830  9.331977e-103
39              mths_since_issue_d:49-52      0.480884   7.625745e-52
40              mths_since_issue_d:53-64      0.235773   2.898279e-15
41              mths_since_issue_d:65-84     -0.016123   5.789051e-01
42                       int_rate:<9.548      0.978050   3.372954e-37
43                 int_rate:9.548-12.025      0.626825   3.419023e-44
44                 int_rate:12.025-15.74      0.363228   9.519253e-23
45                 int_rate:15.74-20.281      0.152210   1.842180e-07
46   mths_since_earliest_cr_line:141-164      0.077088   2.002972e-03
47   mths_since_earliest_cr_line:165-247      0.058768   3.817462e-03
48   mths_since_earliest_cr_line:248-270      0.105457   7.283339e-05
49   mths_since_earliest_cr_line:271-352      0.142418   2.410748e-09
50      mths_since_earliest_cr_line:>352      0.148888   3.558723e-08
51                         delinq_2yrs:0     -0.034353   5.585025e-01
52                       delinq_2yrs:1-3     -0.062974   2.561635e-01
53                      inq_last_6mths:0      0.283303   2.107527e-02
54                    inq_last_6mths:1-2      0.140813   2.510080e-01
55                    inq_last_6mths:3-6     -0.067736   5.822204e-01
56                          open_acc:1-3      0.069358   6.895564e-01
57                         open_acc:4-12     -0.043010   8.002541e-01
58                        open_acc:13-17     -0.066164   6.976365e-01
59                        open_acc:18-22     -0.093754   5.840294e-01
60                        open_acc:23-25     -0.077054   6.609872e-01
61                        open_acc:26-30     -0.054238   7.641166e-01
62                         open_acc:>=31     -0.109168   5.750809e-01
63                           pub_rec:3-4      0.135512   1.543052e-01
64                           pub_rec:>=5      0.093248   6.162906e-01
65                       total_acc:28-51     -0.021158   1.363106e-01
66                        total_acc:>=52      0.031606   4.276334e-01
67                    acc_now_delinq:>=1      0.159981   1.324820e-01
68               total_rev_hi_lim:5K-10K      0.042765   8.251183e-02
69              total_rev_hi_lim:10K-20K      0.008320   7.274677e-01
70              total_rev_hi_lim:20K-30K      0.002484   9.245667e-01
71              total_rev_hi_lim:30K-40K      0.020059   4.960551e-01
72              total_rev_hi_lim:40K-55K      0.033261   3.009045e-01
73              total_rev_hi_lim:55K-95K      0.060838   9.147768e-02
74                 total_rev_hi_lim:>95K      0.199872   4.056206e-04
75                    annual_inc:20K-30K     -0.181832   3.775562e-05
76                    annual_inc:30K-40K     -0.111822   8.799910e-03
77                    annual_inc:40K-50K     -0.013225   7.569391e-01
78                    annual_inc:50K-60K      0.054739   2.061675e-01
79                    annual_inc:60K-70K      0.133314   2.610808e-03
80                    annual_inc:70K-80K      0.206968   4.614634e-06
81                    annual_inc:80K-90K      0.279236   2.686221e-09
82                   annual_inc:90K-100K      0.294193   1.293812e-09
83                  annual_inc:100K-120K      0.373761   9.038476e-15
84                  annual_inc:120K-140K      0.493080   1.563662e-19
85                      annual_inc:>140K      0.399717   2.931242e-15
86                             dti:<=1.4      0.052716   5.629926e-01
87                           dti:1.4-3.5      0.173252   2.605363e-02
88                           dti:3.5-7.7      0.199058   3.746695e-03
89                          dti:7.7-10.5      0.141112   3.832032e-02
90                         dti:10.5-16.1      0.059321   3.704647e-01
91                         dti:16.1-20.3     -0.038178   5.641484e-01
92                         dti:20.3-21.7     -0.048790   4.764644e-01
93                         dti:21.7-22.4     -0.083923   2.447084e-01
94                           dti:22.4-35     -0.120491   6.580677e-02
95        mths_since_last_delinq:Missing      0.072023   2.158310e-01
96           mths_since_last_delinq:4-30      0.120756   2.488625e-02
97          mths_since_last_delinq:31-56      0.147733   1.267304e-02
98           mths_since_last_delinq:>=57      0.099853   9.825878e-02
99        mths_since_last_record:Missing      0.151859   8.934032e-02
100          mths_since_last_record:3-20      0.228861   7.602482e-02
101         mths_since_last_record:21-31      0.155657   1.904373e-01
102         mths_since_last_record:32-80      0.329936   4.100106e-04
103         mths_since_last_record:81-86     -0.028652   7.919033e-01
104           mths_since_last_record:>86      0.062946   4.938083e-01

In [63]:
# We are going to remove some features, the coefficients for all or almost all of the dummy variables for which,
# are not tatistically significant.

# We do that by specifying another list of dummy variables as reference categories, and a list of variables to remove.
# Then, we are going to drop the two datasets from the original list of dummy variables.

# Variables
inputs_train_with_ref_cat = loan_data_inputs_train.loc[: , ['grade:A',
'grade:B',
'grade:C',
'grade:D',
'grade:E',
'grade:F',
'grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'home_ownership:OWN',
'home_ownership:MORTGAGE',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'addr_state:NM_VA',
'addr_state:NY',
'addr_state:OK_TN_MO_LA_MD_NC',
'addr_state:CA',
'addr_state:UT_KY_AZ_NJ',
'addr_state:AR_MI_PA_OH_MN',
'addr_state:RI_MA_DE_SD_IN',
'addr_state:GA_WA_OR',
'addr_state:WI_MT',
'addr_state:TX',
'addr_state:IL_CT',
'addr_state:KS_SC_CO_VT_AK_MS',
'addr_state:WV_NH_WY_DC_ME_ID',
'verification_status:Not Verified',
'verification_status:Source Verified',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'purpose:credit_card',
'purpose:debt_consolidation',
'purpose:oth__med__vacation',
'purpose:major_purch__car__home_impr',
'initial_list_status:f',
'initial_list_status:w',
'term:36',
'term:60',
'emp_length:0',
'emp_length:1',
'emp_length:2-4',
'emp_length:5-6',
'emp_length:7-9',
'emp_length:10',
'mths_since_issue_d:<38',
'mths_since_issue_d:38-39',
'mths_since_issue_d:40-41',
'mths_since_issue_d:42-48',
'mths_since_issue_d:49-52',
'mths_since_issue_d:53-64',
'mths_since_issue_d:65-84',
'mths_since_issue_d:>84',
'int_rate:<9.548',
'int_rate:9.548-12.025',
'int_rate:12.025-15.74',
'int_rate:15.74-20.281',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'mths_since_earliest_cr_line:141-164',
'mths_since_earliest_cr_line:165-247',
'mths_since_earliest_cr_line:248-270',
'mths_since_earliest_cr_line:271-352',
'mths_since_earliest_cr_line:>352',
'inq_last_6mths:0',
'inq_last_6mths:1-2',
'inq_last_6mths:3-6',
'inq_last_6mths:>6',
'acc_now_delinq:0',
'acc_now_delinq:>=1',
'annual_inc:<20K',
'annual_inc:20K-30K',
'annual_inc:30K-40K',
'annual_inc:40K-50K',
'annual_inc:50K-60K',
'annual_inc:60K-70K',
'annual_inc:70K-80K',
'annual_inc:80K-90K',
'annual_inc:90K-100K',
'annual_inc:100K-120K',
'annual_inc:120K-140K',
'annual_inc:>140K',
'dti:<=1.4',
'dti:1.4-3.5',
'dti:3.5-7.7',
'dti:7.7-10.5',
'dti:10.5-16.1',
'dti:16.1-20.3',
'dti:20.3-21.7',
'dti:21.7-22.4',
'dti:22.4-35',
'dti:>35',
'mths_since_last_delinq:Missing',
'mths_since_last_delinq:0-3',
'mths_since_last_delinq:4-30',
'mths_since_last_delinq:31-56',
'mths_since_last_delinq:>=57',
'mths_since_last_record:Missing',
'mths_since_last_record:0-2',
'mths_since_last_record:3-20',
'mths_since_last_record:21-31',
'mths_since_last_record:32-80',
'mths_since_last_record:81-86',
'mths_since_last_record:>86',
]]

In [64]:
ref_categories = ['grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'initial_list_status:f',
'term:60',
'emp_length:0',
'mths_since_issue_d:>84',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'inq_last_6mths:>6',
'acc_now_delinq:0',
'annual_inc:<20K',
'dti:>35',
'mths_since_last_delinq:0-3',
'mths_since_last_record:0-2']

In [65]:
inputs_train = inputs_train_with_ref_cat.drop(ref_categories, axis = 1)
inputs_train.head()

,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,home_ownership:OWN,home_ownership:MORTGAGE,addr_state:NM_VA,addr_state:NY,...,mths_since_last_delinq:Missing,mths_since_last_delinq:4-30,mths_since_last_delinq:31-56,mths_since_last_delinq:>=57,mths_since_last_record:Missing,mths_since_last_record:3-20,mths_since_last_record:21-31,mths_since_last_record:32-80,mths_since_last_record:81-86,mths_since_last_record:>86
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
427211,1,0,0,0,0,0,0,1,0,0,...,1,0,0,0,1,0,0,0,0,0
206088,0,0,1,0,0,0,0,1,0,0,...,0,1,0,0,1,0,0,0,0,0
136020,1,0,0,0,0,0,0,1,0,0,...,0,0,1,0,1,0,0,0,0,0
412305,0,0,0,1,0,0,0,0,0,0,...,0,1,0,0,1,0,0,0,0,0
36159,0,0,1,0,0,0,0,1,0,0,...,1,0,0,0,1,0,0,0,0,0

In [66]:
reg2 = LogisticRegression_with_p_values()
reg2.fit(inputs_train, loan_data_targets_train)

c:\Users\k\anaconda3\envs\creditrisk\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [67]:
feature_name = inputs_train.columns.values

In [68]:
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)
summary_table['Coefficients'] = np.transpose(reg2.coef_)
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg2.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

                           Feature name  Coefficients
0                             Intercept     -0.463330
1                               grade:A      0.942864
2                               grade:B      0.730167
3                               grade:C      0.547289
4                               grade:D      0.372100
5                               grade:E      0.218311
6                               grade:F      0.049030
7                    home_ownership:OWN      0.096190
8               home_ownership:MORTGAGE      0.104737
9                      addr_state:NM_VA      0.044846
10                        addr_state:NY      0.069922
11         addr_state:OK_TN_MO_LA_MD_NC      0.066962
12                        addr_state:CA      0.073659
13               addr_state:UT_KY_AZ_NJ      0.088810
14            addr_state:AR_MI_PA_OH_MN      0.145877
15            addr_state:RI_MA_DE_SD_IN      0.113823
16                  addr_state:GA_WA_OR      0.196644
17                     addr_state:WI_MT      0.243645
18                        addr_state:TX      0.232673
19                     addr_state:IL_CT      0.272130
20         addr_state:KS_SC_CO_VT_AK_MS      0.334345
21         addr_state:WV_NH_WY_DC_ME_ID      0.501561
22     verification_status:Not Verified      0.080365
23  verification_status:Source Verified     -0.013023
24                  purpose:credit_card      0.283290
25           purpose:debt_consolidation      0.177846
26           purpose:oth__med__vacation      0.188264
27  purpose:major_purch__car__home_impr      0.242061
28                initial_list_status:w      0.049319
29                              term:36      0.080711
30                         emp_length:1      0.109178
31                       emp_length:2-4      0.133497
32                       emp_length:5-6      0.100144
33                       emp_length:7-9      0.067044
34                        emp_length:10      0.129904
35               mths_since_issue_d:<38      1.133319
36             mths_since_issue_d:38-39      0.943318
37             mths_since_issue_d:40-41      0.843239
38             mths_since_issue_d:42-48      0.651742
39             mths_since_issue_d:49-52      0.487715
40             mths_since_issue_d:53-64      0.242539
41             mths_since_issue_d:65-84     -0.008368
42                      int_rate:<9.548      0.965410
43                int_rate:9.548-12.025      0.627531
44                int_rate:12.025-15.74      0.362496
45                int_rate:15.74-20.281      0.150002
46  mths_since_earliest_cr_line:141-164      0.076871
47  mths_since_earliest_cr_line:165-247      0.057056
48  mths_since_earliest_cr_line:248-270      0.105700
49  mths_since_earliest_cr_line:271-352      0.145977
50     mths_since_earliest_cr_line:>352      0.153023
51                     inq_last_6mths:0      0.265943
52                   inq_last_6mths:1-2      0.121518
53                   inq_last_6mths:3-6     -0.086156
54                   acc_now_delinq:>=1      0.145208
55                   annual_inc:20K-30K     -0.180762
56                   annual_inc:30K-40K     -0.117121
57                   annual_inc:40K-50K     -0.022238
58                   annual_inc:50K-60K      0.042513
59                   annual_inc:60K-70K      0.121089
60                   annual_inc:70K-80K      0.192124
61                   annual_inc:80K-90K      0.268270
62                  annual_inc:90K-100K      0.279159
63                 annual_inc:100K-120K      0.359531
64                 annual_inc:120K-140K      0.480280
65                     annual_inc:>140K      0.386156
66                            dti:<=1.4      0.057756
67                          dti:1.4-3.5      0.167917
68                          dti:3.5-7.7      0.201357
69                         dti:7.7-10.5      0.134914
70                        dti:10.5-16.1      0.054082
71                        dti:16.1-20.3     -0.047825
72                        dti:20.3-21.7     -0.065848
73                        dti:21.7-22.4     -0.095107
74                          dti:22.4-35     -0.139212
75       mths_since_last_delinq:Missing      0.076772
76          mths_since_last_delinq:4-30      0.100792
77         mths_since_last_delinq:31-56      0.144417
78          mths_since_last_delinq:>=57      0.095076
79       mths_since_last_record:Missing      0.135092
80          mths_since_last_record:3-20      0.232015
81         mths_since_last_record:21-31      0.148963
82         mths_since_last_record:32-80      0.308727
83         mths_since_last_record:81-86     -0.066406
84           mths_since_last_record:>86      0.032461

In [69]:
p_values = reg2.p_values
p_values = np.append(np.nan,np.array(p_values))
summary_table['p_values'] = p_values
summary_table

                           Feature name  Coefficients       p_values
0                             Intercept     -0.463330            NaN
1                               grade:A      0.942864   5.290854e-25
2                               grade:B      0.730167   2.500102e-32
3                               grade:C      0.547289   1.097826e-21
4                               grade:D      0.372100   7.008305e-12
5                               grade:E      0.218311   5.910955e-06
6                               grade:F      0.049030   3.272023e-01
7                    home_ownership:OWN      0.096190   1.869832e-06
8               home_ownership:MORTGAGE      0.104737   1.177531e-16
9                      addr_state:NM_VA      0.044846   1.609074e-01
10                        addr_state:NY      0.069922   3.871333e-03
11         addr_state:OK_TN_MO_LA_MD_NC      0.066962   3.771931e-03
12                        addr_state:CA      0.073659   5.001196e-04
13               addr_state:UT_KY_AZ_NJ      0.088810   3.588703e-04
14            addr_state:AR_MI_PA_OH_MN      0.145877   8.951952e-11
15            addr_state:RI_MA_DE_SD_IN      0.113823   1.364704e-04
16                  addr_state:GA_WA_OR      0.196644   1.604553e-13
17                     addr_state:WI_MT      0.243645   2.878467e-07
18                        addr_state:TX      0.232673   3.161379e-19
19                     addr_state:IL_CT      0.272130   1.140705e-20
20         addr_state:KS_SC_CO_VT_AK_MS      0.334345   2.344800e-27
21         addr_state:WV_NH_WY_DC_ME_ID      0.501561   1.556895e-21
22     verification_status:Not Verified      0.080365   3.652312e-08
23  verification_status:Source Verified     -0.013023   3.323415e-01
24                  purpose:credit_card      0.283290   1.894512e-23
25           purpose:debt_consolidation      0.177846   9.931382e-12
26           purpose:oth__med__vacation      0.188264   1.571496e-09
27  purpose:major_purch__car__home_impr      0.242061   1.048582e-14
28                initial_list_status:w      0.049319   1.584992e-04
29                              term:36      0.080711   7.797032e-09
30                         emp_length:1      0.109178   2.578492e-05
31                       emp_length:2-4      0.133497   1.461968e-12
32                       emp_length:5-6      0.100144   2.851696e-06
33                       emp_length:7-9      0.067044   1.254221e-03
34                        emp_length:10      0.129904   1.752300e-12
35               mths_since_issue_d:<38      1.133319  3.241765e-201
36             mths_since_issue_d:38-39      0.943318  6.263131e-175
37             mths_since_issue_d:40-41      0.843239  9.705247e-148
38             mths_since_issue_d:42-48      0.651742  8.878595e-114
39             mths_since_issue_d:49-52      0.487715   1.244455e-56
40             mths_since_issue_d:53-64      0.242539   4.387386e-17
41             mths_since_issue_d:65-84     -0.008368   7.721670e-01
42                      int_rate:<9.548      0.965410   9.946567e-37
43                int_rate:9.548-12.025      0.627531   8.080451e-45
44                int_rate:12.025-15.74      0.362496   5.836116e-23
45                int_rate:15.74-20.281      0.150002   2.364205e-07
46  mths_since_earliest_cr_line:141-164      0.076871   1.984379e-03
47  mths_since_earliest_cr_line:165-247      0.057056   4.398629e-03
48  mths_since_earliest_cr_line:248-270      0.105700   5.554682e-05
49  mths_since_earliest_cr_line:271-352      0.145977   4.359762e-10
50     mths_since_earliest_cr_line:>352      0.153023   7.642808e-09
51                     inq_last_6mths:0      0.265943   4.237144e-03
52                   inq_last_6mths:1-2      0.121518   1.907875e-01
53                   inq_last_6mths:3-6     -0.086156   3.562868e-01
54                   acc_now_delinq:>=1      0.145208   1.730173e-01
55                   annual_inc:20K-30K     -0.180762   2.794538e-05
56                   annual_inc:30K-40K     -0.117121   4.821034e-03
57                   annual_inc:40K-50K     -0.022238   5.920574e-01
58                   annual_inc:50K-60K      0.042513   3.114878e-01
59                   annual_inc:60K-70K      0.121089   4.780662e-03
60                   annual_inc:70K-80K      0.192124   1.115034e-05
61                   annual_inc:80K-90K      0.268270   3.601624e-09
62                  annual_inc:90K-100K      0.279159   2.773136e-09
63                 annual_inc:100K-120K      0.359531   1.196604e-14
64                 annual_inc:120K-140K      0.480280   1.222851e-19
65                     annual_inc:>140K      0.386156   1.632868e-15
66                            dti:<=1.4      0.057756   5.009796e-01
67                          dti:1.4-3.5      0.167917   2.134897e-02
68                          dti:3.5-7.7      0.201357   1.619233e-03
69                         dti:7.7-10.5      0.134914   3.366893e-02
70                        dti:10.5-16.1      0.054082   3.801225e-01
71                        dti:16.1-20.3     -0.047825   4.382530e-01
72                        dti:20.3-21.7     -0.065848   3.052874e-01
73                        dti:21.7-22.4     -0.095107   1.625702e-01
74                          dti:22.4-35     -0.139212   2.261683e-02
75       mths_since_last_delinq:Missing      0.076772   1.486794e-01
76          mths_since_last_delinq:4-30      0.100792   6.044849e-02
77         mths_since_last_delinq:31-56      0.144417   7.876384e-03
78          mths_since_last_delinq:>=57      0.095076   8.721462e-02
79       mths_since_last_record:Missing      0.135092   1.098844e-01
80          mths_since_last_record:3-20      0.232015   6.243654e-02
81         mths_since_last_record:21-31      0.148963   1.939154e-01
82         mths_since_last_record:32-80      0.308727   4.846149e-04
83         mths_since_last_record:81-86     -0.066406   5.245864e-01
84           mths_since_last_record:>86      0.032461   7.098544e-01

In [70]:
import pickle

In [71]:
pickle.dump(reg2, open('model/pd_model.sav', 'wb'))